name: relaxation
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^7.2.0
  # Bloc for state management
  flutter_bloc: ^7.0.1
  provider: ^6.0.0
  # Value equality
  equatable: ^2.0.3
  # Functionalprogramming thingies
  fpdart: ^0.0.8
  # Remote API
  # connectivity:
  # http: ^0.12.0+2

  flutter_audio_query: ^0.3.5+6
  just_audio: ^0.9.10
  audio_video_progress_bar:

  # Local cache
  shared_preferences: ^2.0.6
  cupertino_icons: ^1.0.2

  # Fonts
  google_fonts: ^2.1.0

  # Icons
  font_awesome_flutter: ^9.1.0

  # toggle
  toggle_switch: ^1.2.0

  # dialog
  ndialog: ^4.1.0
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.0-dev.7
  freezed_annotation:

  # bottom_navigation_bar
  salomon_bottom_bar: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.11
  build_runner:
  freezed:

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
